### ISSUE TITLE
Bisa beritahu commant listnya

### ISSUE THREAD

**Issue by aqiyzx** [NazwaS/termux-whatsapp-bot#17]
Soalnya saya menggunakan ini sudah scan qr complete tapi ga tau commant listnya untuk botnya kalo ada yang tau boleh beritahu commant list untuk bot ini dari tadi nyari ga ketemu di file .../music/...
dan bot tidak mengetahui Unregistered commant from : nomor_anda

terima kasih.

**Comment by RyzRdy** [comment]
Ketik saja .help

**Comment by rvnzxpl** [comment]
Issue Closed
