### ISSUE TITLE
What I Do After Connecting

### ISSUE THREAD

**Issue by dilshad0101** [NazwaS/termux-whatsapp-bot#2]
I am Connected By Scanning Qr Code But How To Start It On Whatsapp What Is Prefix

**Comment by NazwaS** [comment]
A prefix is = ```.```

**Comment by NazwaS** [comment]
A prefix is = ```.```

You can change prefix on [this section](https://github.com/NazwaS/termux-whatsapp-bot/blob/main/index.js#L49)
