### ISSUE TITLE
Error issue(?)

### ISSUE THREAD

**Issue by rndrdp** [NazwaS/termux-whatsapp-bot#26]
~> [EXEC] 11/02 12:35:19 menu from 628****** in tes grup args : 0
[WARN] Unregistered Command from 628******

nyoba bot di grup malah left sendiri pak

**Comment by NazwaS** [comment]
Itu limit member

**Comment by NazwaS** [comment]
Ubah di option.json

**Comment by rndrdp** [comment]
Okok tak coba dulu pak

**Comment by rndrdp** [comment]
sip bisa pak, terima kasih banyak
