### ISSUE TITLE
Cuma kasih tau sih

### ISSUE THREAD

**Issue by firmantsani** [NazwaS/termux-whatsapp-bot#29]
![IMG_20210213_231528](https://user-images.githubusercontent.com/45849550/107854865-691f5700-6e51-11eb-9dfd-361b908e81d1.jpg)
tapi udh solved sih lastindexOf diganti jadi last"I"ndexOf
ganti huruf i ke huruf besar
Izin pake bot nya

**Comment by NazwaS** [comment]
Sib, nice ingfo
