### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by harieyadi** [NazwaS/termux-whatsapp-bot#3]
![Screenshot_2021-01-14-20-02-55](https://user-images.githubusercontent.com/73776729/104588919-1280fa80-56a4-11eb-8780-37e1ba38d403.png)

**Comment by NazwaS** [comment]
Npm nya gak support kak,

**Comment by NazwaS** [comment]
Coba turunin versi npm nya ke versi ```6.14.10```

**Comment by harieyadi** [comment]
Nurunin nya dimana?

**Comment by AD16JR** [comment]
Aku juga gitu :'

Pada tanggal Kam, 14 Jan 2021 23.25, harieyadi <notifications@github.com>
menulis:

**Comment by NazwaS** [comment]
> Nurunin nya dimana?

Coba:

```bash
npm i npm@6.14.10 -g
```

**Comment by harieyadi** [comment]
> > Nurunin nya dimana?
> 
> Coba:
> 
> ```shell
> npm i npm@6.14.10 -g
> ```

All dependencies have been installed, please run the command "npm start" to immediately start the script
Updates : fix Bugs
$ npm start

> termux-whatsapp-bot@0.0.2 start /data/data/com.termux/files/home/termux-whatsapp-bot
> node index.js

internal/modules/cjs/loader.js:798
    throw err;
    ^

Error: Cannot find module 'fs/promises'
Require stack:
- /data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js
- /data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/index.js
- /data/data/com.termux/files/home/termux-whatsapp-bot/lib/functions.js
- /data/data/com.termux/files/home/termux-whatsapp-bot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
    at Function.Module._load (internal/modules/cjs/loader.js:688:27)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js',
    '/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/index.js',
    '/data/data/com.termux/files/home/termux-whatsapp-bot/lib/functions

**Comment by zannz** [comment]
Saya baru saja menulis ".help"


(node:20196) UnhandledPromiseRejectionWarning: Error: marker was not found
    at decodeScan (/data/data/com.termux/files/home/termux-bot/node_modules/jpeg-js/lib/decoder.js:344:15)
    at constructor.parse (/data/data/com.termux/files/home/termux-bot/node_modules/jpeg-js/lib/decoder.js:804:29)
    at Object.decode [as image/jpeg] (/data/data/com.termux/files/home/termux-bot/node_modules/jpeg-js/lib/decoder.js:1096:11)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/termux-bot/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/data/data/com.termux/files/home/termux-bot/node_modules/@jimp/core/dist/index.js:431:32)
    at /data/data/com.termux/files/home/termux-bot/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(Use node --trace-warnings ... to show where the warning was created)
(node:20196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NazwaS** [comment]
> > > Nurunin nya dimana?
> > 
> > 
> > Coba:
> > ```shell
> > npm i npm@6.14.10 -g
> > ```
> 
> All dependencies have been installed, please run the command "npm start" to immediately start the script
> Updates : fix Bugs
> $ npm start
> 
> > termux-whatsapp-bot@0.0.2 start /data/data/com.termux/files/home/termux-whatsapp-bot
> > node index.js
> 
> internal/modules/cjs/loader.js:798
> throw err;
> ^
> 
> Error: Cannot find module 'fs/promises'
> Require stack:
> 
> * /data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js
> * /data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/index.js
> * /data/data/com.termux/files/home/termux-whatsapp-bot/lib/functions.js
> * /data/data/com.termux/files/home/termux-whatsapp-bot/index.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:795:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:688:27)
>   at Module.require (internal/modules/cjs/loader.js:850:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js:40:18)
>   at Module._compile (internal/modules/cjs/loader.js:958:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
>   at Module.load (internal/modules/cjs/loader.js:813:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:14)
>   at Module.require (internal/modules/cjs/loader.js:850:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/validateInput.js',
>   '/data/data/com.termux/files/home/termux-whatsapp-bot/node_modules/imgbb-uploader/lib/cjs/index.js',
>   '/data/data/com.termux/files/home/termux-whatsapp-bot/lib/functions

Coba:

```bash
> rm -rf node_modules package-lock.json
> npm cache clean -f
> npm i
```bash

**Comment by zannz** [comment]
![Screenshot_2021-01-15-17-20-26-342_com termux](https://user-images.githubusercontent.com/77357047/104774900-38ff6e00-5756-11eb-811d-541cd93ad80b.jpg)

**Comment by NazwaS** [comment]
Itu error dari image nya, udh kuhapus imagenya kok...

**Comment by zannz** [comment]
![Screenshot_2021-01-15-23-04-18-781_com termux](https://user-images.githubusercontent.com/77357047/104794406-2dc43680-5786-11eb-9296-82b683542289.jpg)
:/

**Comment by NazwaS** [comment]
Bntar ;/

**Comment by NazwaS** [comment]
Dah tuh, coba lagi

**Comment by NazwaS** [comment]
Ku close ya...
