### ISSUE TITLE
Register eror

### ISSUE THREAD

**Issue by elssword** [NazwaS/termux-whatsapp-bot#30]
Kak pas register new user kok eror tulisannya ReferenceError: isRegistered is not defined
![Screenshot_2021-02-15-07-24-21-608_com termux](https://user-images.githubusercontent.com/48546605/107893634-da006500-6f5e-11eb-90ad-9b67c4bea758.jpg)

**Comment by NazwaS** [comment]
Oh, tnx. Nice ingfo
