### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by dejarpa** [NazwaS/termux-whatsapp-bot#37]
Ig Stalk error 
#37

**Comment by NazwaS** [comment]
screenshots and post here

**Comment by dejarpa** [comment]
> screenshots and post here

ni ka
![Uploading Screenshot_2021-02-16-15-14-01-517_com.termux.jpg…]()

**Comment by dejarpa** [comment]
![Screenshot_2021-02-16-15-14-01-517_com termux](https://user-images.githubusercontent.com/68485598/108035798-f63cf880-7069-11eb-9301-1d49607f4e4d.jpg)

**Comment by NazwaS** [comment]
Done.

**Comment by NazwaS** [comment]
Issue closed

**Comment by dejarpa** [comment]
makasih

**Comment by dejarpa** [comment]
![IMG_20210217_061758](https://user-images.githubusercontent.com/68485598/108133966-fed41400-70e7-11eb-8215-370f193abc8e.jpg)
erorr nya ga paham aku, udh ku cek

**Comment by NazwaS** [comment]
Njir

**Comment by dejarpa** [comment]
whehee

**Comment by NazwaS** [comment]
Dah, tadi ada yg lupa :|

**Comment by NazwaS** [comment]
Issue closed
