### ISSUE TITLE
p

### ISSUE THREAD

**Issue by Rianfirnanda** [NazwaS/termux-whatsapp-bot#7]

**Comment by NazwaS** [comment]
??

**Comment by ZefianAlfian** [comment]
> ??

kenapa isu ku di close?:(

**Comment by NazwaS** [comment]
:V emg ada masalah apa?

**Comment by ZefianAlfian** [comment]
> :V emg ada masalah apa?

pas npm i error semua

**Comment by Rianfirnanda** [comment]
bang,kenapa pas npm i error semua, tolong di fix bang..

**Comment by ZefianAlfian** [comment]
> :V emg ada masalah apa?

aku foto in mau? eh ngirim foto disini gimana, minta nomor whatsapp nya aja👉

**Comment by NazwaS** [comment]
+1 (254) 212-3926

**Comment by ZefianAlfian** [comment]
> +1 (254) 212-3926 :/

gamau maunya nomor aslii

**Comment by RyzRdy** [comment]
Itu asli :v

**Comment by ZefianAlfian** [comment]
> Itu asli :v

oooo yaudah , 
![Screenshot_20210119_100905](https://user-images.githubusercontent.com/70304409/104983056-95a4a680-5a3e-11eb-8810-6fdea7d741f9.png)

**Comment by RyzRdy** [comment]
> > Itu asli :v
> 
> oooo yaudah ,
> ![Screenshot_20210119_100905](https://user-images.githubusercontent.com/70304409/104983056-95a4a680-5a3e-11eb-8810-6fdea7d741f9.png)

Bash install.sh

**Comment by ZefianAlfian** [comment]
> > > Itu asli :v
> > 
> > 
> > oooo yaudah ,
> > ![Screenshot_20210119_100905](https://user-images.githubusercontent.com/70304409/104983056-95a4a680-5a3e-11eb-8810-6fdea7d741f9.png)
> 
> Bash install.sh

tetep error syg

**Comment by RyzRdy** [comment]
yang eror apanya?

**Comment by ZefianAlfian** [comment]
> yang eror apanya?

engga tau , nomor whatsapp kamu sini aku kirim video pas install nya

**Comment by RyzRdy** [comment]
> > yang eror apanya?
> 
> engga tau , nomor whatsapp kamu sini aku kirim video pas install nya

082147334254

**Comment by ZefianAlfian** [comment]
> > > yang eror apanya?
> > 
> > 
> > engga tau , nomor whatsapp kamu sini aku kirim video pas install nya
> 
> 082147334265

gabisa

**Comment by RyzRdy** [comment]
082147334265 tu

**Comment by RyzRdy** [comment]
wa.me/6282147334265
